- name: Varibles
  hosts: node
  vars:
    Course: "DevOps -"
    Duration: "120 hr"
    Trainer: Siva kumar reddy
  tasks:
   - name: Intialization
     ansible.bulitin.debug:
      msg: "This {{Course}}course total {{Duration}}and trined by {{Trainer}}"