- name: conditions
  hosts: local
  connection: local
  vars_prompt: 
  - name: my_number
    prompt: enter number
    praivate: false
  tasks:
  - name: print if less than 10
    ansible.builtin.debug:
      msg: number {{my_number}} is less than 10
    when: my_number < 10

  - name: print if less than 10
    ansible.builtin.debug:
      msg: number{{my_number}} is equals to 10 or above
    when: my_number >= 10