- name: user creation
  hosts: localhost
  become: yes
  tasks: 
  - name: verify user
    ansible.builtin.command: id expense
    register: USER

  - name: print user info
    ansible.builtin.debug:
      msg: "user info {{USER}}"
