- name: demo on filters/funtions
  hosts: localhost
  tasks:
  - name: print the varible
    ansible.builtin.debug:
      msg: "Hello  {{couse | default('Ansible')}}" # assign default value to varible

  - name: uppercase
    vars:
      greetings: "good morning"
    ansible.builtin.debug:
      msg: "Hi {{greetings | upper}}"
  
  - name: lowercase
    vars:
      greetings: "goOd MornIng"
    ansible.builtin.debug:
      msg: "Hi {{greetings | lower}}"
  
  - name: min and max
    vars:
      numbers: [1,4,8,9,12]
    ansible.builtin.debug:
      msg: "MAX num {{number | max}} MIN num {{number| min}}"